//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersianShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Field()
        {
            this.UserFieldPermission = new HashSet<UserFieldPermission>();
        }
    
        public int FieldId { get; set; }
        public int FormId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool v1 { get; set; }
        public bool v2 { get; set; }
        public bool v3 { get; set; }
        public bool v4 { get; set; }
        public bool v5 { get; set; }
        public bool v6 { get; set; }
        public bool v7 { get; set; }
        public bool v8 { get; set; }
        public bool v9 { get; set; }
        public bool v10 { get; set; }
    
        public virtual Form Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFieldPermission> UserFieldPermission { get; set; }
    }
}
