//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersianShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Form()
        {
            this.Field = new HashSet<Field>();
            this.Menu = new HashSet<Menu>();
            this.UserFormPermission = new HashSet<UserFormPermission>();
        }
    
        public int FormId { get; set; }
        public string Title { get; set; }
        public string NameSpace { get; set; }
        public string Class { get; set; }
        public string Description { get; set; }
        public Nullable<bool> v3 { get; set; }
        public Nullable<bool> v1 { get; set; }
        public Nullable<bool> v2 { get; set; }
        public Nullable<bool> v4 { get; set; }
        public Nullable<bool> v5 { get; set; }
        public Nullable<bool> v6 { get; set; }
        public Nullable<bool> v7 { get; set; }
        public Nullable<bool> v8 { get; set; }
        public Nullable<bool> v9 { get; set; }
        public Nullable<bool> v10 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Field> Field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFormPermission> UserFormPermission { get; set; }
    }
}
