//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersianShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class overal_setting
    {
        public int id { get; set; }
        public string dis { get; set; }
        public long value { get; set; }
        public string Address { get; set; }
        public Nullable<int> TabOrder { get; set; }
        public string ExternalExplain { get; set; }
    }
}
