//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersianShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSystemPermission
    {
        public int ID { get; set; }
        public Nullable<int> PermissionID { get; set; }
        public Nullable<int> SubSystemID { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual sys_users sys_users { get; set; }
        public virtual SubSystem SubSystem { get; set; }
    }
}
