//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersianShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPersonalizationForFont
    {
        public int PersonalizationFontID { get; set; }
        public int UserID { get; set; }
        public int ControlNameID { get; set; }
        public int FontSize { get; set; }
    
        public virtual sys_users sys_users { get; set; }
    }
}
